services:
  app:
    build: .
    volumes:
      - .env.docker:/python-docker/.env
      - .env.testing.docker:/python-docker/.env.testing
    ports:
      - 6000:5000
    depends_on:
      db:
        condition: service_healthy
      test_db:
        condition: service_healthy
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
  test_db:
    image: postgres:latest
    ports:
      - 5434:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10


