services:
  app:
    build: .
    env_file:
      - .env.docker
#      - .env.docker:/home/runner/work/VoterJson/VoterJson/.env
#      - .env.docker:/python-docker/.env
    ports:
      - 6000:5000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - .env.docker
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
#  test_db:
#    image: postgres:latest
#    ports:
#      - 5434:5432
#    env_file:
#      - .env.testing
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10


