name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --fail-under=7.5
    - name: Build docker and launch flask
      run: |
        docker-compose up --build -d
    - name: Init db in flask app
      run: |  
        docker-compose exec app flask --app voterjsonr init-db
    - name: Test with pytest
      run: |
        docker-compose exec app pytest
